# Generated by Django 2.0.6 on 2018-08-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='painting_type',
            field=models.CharField(choices=[('L', 'Landscape'), ('P', 'Portrait'), ('A', 'Animals'), ('S', 'Still Life')], default='L', max_length=1),
        ),
    ]
