# Generated by Django 2.0.6 on 2018-08-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180810_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.CharField(choices=[('B', 'Beginner'), ('A', 'Advanced'), ('N', 'N/A')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='medium',
            field=models.CharField(choices=[('O', 'Oil'), ('A', 'Acrylic'), ('W', 'Watercolour'), ('C', 'Charcoal')], default='O', max_length=1),
        ),
    ]
